djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('knup/', include('knup.urls'))
]

knup/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'knup'
urlpatterns = [
    path('', views.FileView.index),
    path('upload/', views.FileView.file_upload, name='file_upload'),
    path('list/', views.FileView.file_list, name='file_list'),
    path('preview/', views.FileView.file_preview, name='file_preview'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knup/models.py
from django.db import models

# Create your models here.
class File(models.Model):
    originalname = models.CharField(max_length=100)
    storedname = models.FileField(null=True, blank=True, upload_to="", max_length=200)
    userid = models.IntegerField()
    storeddate = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.storedname

    class Meta:
        ordering = ['storeddate']
        verbose_name = 'file'

knup/forms.py
from django import forms
from .models import File
from django.forms import ClearableFileInput

class UploadForm(forms.ModelForm):
    class Meta:
        model = File
        fields = {'storedname'}
        widgets = {
            'storedname': ClearableFileInput(attrs={'multiple': True}),
        }

knup/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.contrib.auth.hashers import make_password

from rest_framework.parsers import JSONParser
from .models import File
from .serializers import FileSerializer
from .forms import UploadForm

from pathlib import Path
import os

class FileView():

    @csrf_exempt
    def index(request):
        
        return render(request, 'knup/index.html', {})

    @csrf_exempt
    def file_list(request):

        query_set = File.objects.all().filter(userid=12345)
        serializer = FileSerializer(query_set, many=True)

        # return JsonResponse(serializer.data, safe=False)
        return render(request, 'knup/list.html', {
            'data': serializer.data
        })

    @csrf_exempt
    def file_preview(request):

        file_name = request.POST['file']
        p, fn = os.path.split(file_name)
        file_path = os.path.join(settings.MEDIA_ROOT, fn)
        
        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                res = HttpResponse(fh.read(), content_type="application/pdf")
                return res

    @csrf_exempt
    def file_upload(request):
        if request.method == 'POST':
            form = UploadForm(request.POST, request.FILES)

            files = request.FILES.getlist('storedname')

            if form.is_valid():
                
                for idx, f in enumerate(files):
                    
                    originalname = f.name
                    storedname = make_password(f.name)
                    print(storedname)
                    f.name = storedname

                    file_instance = File(originalname=originalname, storedname=f, userid=12345)
                    file_instance.save()

                return redirect('knup:file_list')

        else:
            form = UploadForm()

        return render(request, 'knup/upload.html', {
            'form': form
        })

templates/knup/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="content-Type" content="text/html"; charset=UTF-8>
		<title>KNUP</title>
	</head>
	
	<body>
		<p>KNUP</p>
		{% block content %}
		{% endblock %}
	</body>
</html>

templates/knup/list.html
{% extends 'knup/index.html' %}

{% block content %}
    <h2>The image has been uploaded!!</h2>

    {% for d in data %}
        <form action="{% url 'knup:file_preview' %}" method="post" target="_blank">
        {% csrf_token %}
            <input type="hidden" name="file" value="{{ d.storedname }}">
            <button type="submit">{{ d.originalname }}</button>
        </form>
        <br>
    {% endfor %}

{% endblock %}

templates/knup/upload.html
{% extends 'knup/index.html' %}

{% block content %}
    <h2>Upload Image</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">UploadImage</button>
    </form>
{% endblock%}